#!/bin/bash
################################################################################
# start_next_dev_cycle.sh
#
# Post-merge GitOps script. Finds the oldest open issue in First-ADE/first-ade,
# creates a dedicated feature branch, and opens a Draft Pull Request.
################################################################################

set -e

CORE_REPO="First-ADE/first-ade"

echo "🔍 Finding next open dev cycle issue in $CORE_REPO..."

# 1. Fetch oldest open issue
ISSUE_JSON=$(gh issue list -R "$CORE_REPO" --json number,title,body --jq "sort_by(.number) | .[0]" 2>/dev/null || echo "")

if [ -z "$ISSUE_JSON" ] || [ "$ISSUE_JSON" = "null" ]; then
  echo "✅ No open issues found in $CORE_REPO. All development cycles complete!"
  exit 0
fi

NUMBER=$(echo "$ISSUE_JSON" | jq -r '.number')
TITLE=$(echo "$ISSUE_JSON" | jq -r '.title')
BODY=$(echo "$ISSUE_JSON" | jq -r '.body')

echo "🎯 Found target issue: #$NUMBER - $TITLE"

# 2. Sanitize title to generate a valid branch slug
# e.g., "[US-4] Traceability Validation (P2)" -> "us-4-traceability-validation-p2"
CLEAN_TITLE=$(echo "$TITLE" | tr '[:upper:]' '[:lower:]' | sed -e 's/\[//g' -e 's/\]//g' -e 's/[:()]/ /g' -e 's/[^a-z0-9]/-/g' -e 's/-\+/-/g' -e 's/^-//g' -e 's/-$//g')
BRANCH_NAME="feat/issue-${NUMBER}-${CLEAN_TITLE}"

echo "🌿 Target branch name: $BRANCH_NAME"

# 3. Check if branch already exists remotely
if git ls-remote --heads origin "$BRANCH_NAME" | grep -q "$BRANCH_NAME"; then
  echo "⚠️ Remote branch $BRANCH_NAME already exists. Skipping branch creation."
  exit 0
fi

# 4. Create and push branch with an empty commit to allow PR creation
echo "🚀 Creating branch $BRANCH_NAME off main..."
git checkout -b "$BRANCH_NAME" origin/main
echo "🚀 Creating initial empty commit for GitOps Dev Cycle..."
git commit --allow-empty -m "chore(dev-cycle): initialize branch for issue #$NUMBER"
echo "🚀 Pushing branch to remote..."
git push origin "$BRANCH_NAME"

# 5. Open Draft Pull Request in the current repository
PR_TITLE="feat: $TITLE (Draft)"
PR_BODY="## 🤖 Automated Dev Cycle Kicked Off

This Draft PR was auto-generated by the post-merge GitOps workflow to begin development on the next prioritized task.

### 🎯 Objective
- **Linked Issue:** $CORE_REPO#$NUMBER
- **Title:** $TITLE

### 📋 Original Issue Description
$BODY

---
*Created by GitOps Dev-Cycle Trigger* · Branch: \`$BRANCH_NAME\`"

echo "📄 Creating Draft Pull Request..."
PR_URL=$(gh pr create --draft --title "$PR_TITLE" --body "$PR_BODY" --head "$BRANCH_NAME" --base main || echo "")

if [ -n "$PR_URL" ]; then
  echo "🎉 Successfully created Draft PR: $PR_URL"
  # 6. Post a comment on the original issue linking the draft PR
  COMMENT_BODY="🤖 A development cycle has been successfully initiated for this task.

🌿 **Branch:** \`$BRANCH_NAME\`
📄 **Draft PR:** $PR_URL

Happy coding!"
  gh issue comment "$NUMBER" -R "$CORE_REPO" -b "$COMMENT_BODY"
  echo "💬 Comment posted on issue #$NUMBER"
else
  echo "⚠️ Failed to automatically create draft PR (PR might already exist)."
fi
