#!/usr/bin/env pwsh
<#!
.SYNOPSIS
  Post-merge GitOps script for Windows/PowerShell
.DESCRIPTION
  Finds the oldest open issue in First-ADE/first-ade,
  creates a dedicated feature branch, and opens a Draft Pull Request.
.EXAMPLE
  ./scripts/start_next_dev_cycle.ps1
#>

$ErrorActionPreference = 'Stop'

# UTF-8 Console output enforcement
if ($PSVersionTable.PSVersion.Major -ge 5) {
    [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
}

$CORE_REPO = "First-ADE/first-ade"

Write-Host "🔍 Finding next open dev cycle issue in $CORE_REPO..." -ForegroundColor Cyan

# 1. Fetch oldest open issue using gh CLI
$issueJson = ""
try {
    $issueJson = gh issue list -R $CORE_REPO --json number,title,body --limit 100 2>$null
} catch {
    Write-Host "⚠️ Failed to run gh CLI. Ensure GitHub CLI is installed and authenticated." -ForegroundColor Yellow
    exit 0
}

if ([string]::IsNullOrEmpty($issueJson) -or $issueJson -eq "[]" -or $issueJson -eq "null") {
    Write-Host "✅ No open issues found in $CORE_REPO. All development cycles complete!" -ForegroundColor Green
    exit 0
}

# Parse and sort issues to find the oldest (smallest number)
$issues = $issueJson | ConvertFrom-Json
$oldestIssue = $issues | Sort-Object number | Select-Object -First 1

if ($null -eq $oldestIssue) {
    Write-Host "✅ No open issues found in $CORE_REPO. All development cycles complete!" -ForegroundColor Green
    exit 0
}

$number = $oldestIssue.number
$title = $oldestIssue.title
$body = $oldestIssue.body

Write-Host "🎯 Found target issue: #$number - $title" -ForegroundColor Green

# 2. Sanitize title to generate a valid branch slug
# Lowercase, replace non-alphanumeric with hyphen, compress multiple hyphens, trim hyphens
$cleanTitle = $title.ToLower()
$cleanTitle = $cleanTitle -replace '\[|\]', ''
$cleanTitle = $cleanTitle -replace '[:()\/]', ' '
$cleanTitle = $cleanTitle -replace '[^a-z0-9]', '-'
$cleanTitle = $cleanTitle -replace '-+', '-'
$cleanTitle = $cleanTitle.Trim('-')

$branchName = "feat/issue-$number-$cleanTitle"
Write-Host "🌿 Target branch name: $branchName" -ForegroundColor Cyan

# 3. Check if branch already exists remotely
$lsRemote = git ls-remote --heads origin $branchName 2>$null
if (-not [string]::IsNullOrEmpty($lsRemote) -and $lsRemote -match $branchName) {
    Write-Host "⚠️ Remote branch $branchName already exists. Skipping branch creation." -ForegroundColor Yellow
    exit 0
}

# 4. Create and push branch with empty commit
Write-Host "🚀 Creating branch $branchName off main..." -ForegroundColor Cyan
git checkout -b $branchName origin/main

Write-Host "🚀 Creating initial empty commit for GitOps Dev Cycle..." -ForegroundColor Cyan
git commit --allow-empty -m "chore(dev-cycle): initialize branch for issue #$number"

Write-Host "🚀 Pushing branch to remote..." -ForegroundColor Cyan
git push origin $branchName

# 5. Open Draft Pull Request in current repository
$prTitle = "feat: $title (Draft)"
$prBody = @"
## 🤖 Automated Dev Cycle Kicked Off

This Draft PR was auto-generated by the post-merge GitOps workflow to begin development on the next prioritized task.

### 🎯 Objective
- **Linked Issue:** $CORE_REPO#$number
- **Title:** $title

### 📋 Original Issue Description
$body

---
*Created by GitOps Dev-Cycle Trigger* · Branch: \`$branchName\`
"@

Write-Host "📄 Creating Draft Pull Request..." -ForegroundColor Cyan
$prUrl = ""
try {
    $prUrl = gh pr create --draft --title $prTitle --body $prBody --head $branchName --base main 2>$null
} catch {}

if (-not [string]::IsNullOrEmpty($prUrl)) {
    Write-Host "🎉 Successfully created Draft PR: $prUrl" -ForegroundColor Green
    
    # 6. Post comment on original issue linking the draft PR
    $commentBody = @"
🤖 A development cycle has been successfully initiated for this task.

🌿 **Branch:** \`$branchName\`
📄 **Draft PR:** $prUrl

Happy coding!
"@
    try {
        gh issue comment $number -R $CORE_REPO -b $commentBody | Out-Null
        Write-Host "💬 Comment posted on issue #$number" -ForegroundColor Green
    } catch {
        Write-Host "⚠️ Failed to comment on issue #$number" -ForegroundColor Yellow
    }
} else {
    Write-Host "⚠️ Failed to automatically create draft PR (PR might already exist)." -ForegroundColor Yellow
}
exit 0
